AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create Bedrock Data Automation project with driving license blueprint'

Resources:
  DrivingLicenseBlueprint:
    Type: AWS::Bedrock::Blueprint
    Properties:
      BlueprintName: driving-license-blueprint
      Type: DOCUMENT
      Schema:
        $schema: "http://json-schema.org/draft-07/schema#"
        description: "blueprint to extract fields from a driving license"
        class: "driving-license"
        type: "object"
        definitions: {}
        properties:
          License Number:
            type: "string"
            inferenceType: "explicit"
            instruction: "The unique identifier number for the driver's license"
          Date of Birth:
            type: "string"
            inferenceType: "explicit"
            instruction: "The date of birth of the license holder"
          Issue Date:
            type: "string"
            inferenceType: "explicit"
            instruction: "The date the driver's license was issued"
          Expiration Date:
            type: "string"
            inferenceType: "explicit"
            instruction: "The date the driver's license expires"
          Name:
            type: "string"
            inferenceType: "explicit"
            instruction: "The full name of the license holder"
          Address:
            type: "string"
            inferenceType: "explicit"
            instruction: "The residential address of the license holder"
          License Class:
            type: "string"
            inferenceType: "explicit"
            instruction: "The class of driver's license held by the license holder"
          State:
            type: "string"
            inferenceType: "explicit"
            instruction: "The state that issued the driver's license"
          Organ Donor:
            type: "boolean"
            inferenceType: "explicit"
            instruction: "Indicates if the license holder is an organ donor"
          Restrictions:
            type: "string"
            inferenceType: "explicit"
            instruction: "Any restrictions on the driver's license"
          Sex:
            type: "string"
            inferenceType: "explicit"
            instruction: "The sex of the license holder"
          Height:
            type: "string"
            inferenceType: "explicit"
            instruction: "The height of the license holder"
          Eye Color:
            type: "string"
            inferenceType: "explicit"
            instruction: "The eye color of the license holder"
          Charge:
            type: "number"
            inferenceType: "explicit"
            instruction: "The charge amount for the driver's license"

  BDAProject:
    Type: AWS::Bedrock::DataAutomationProject
    DependsOn: DrivingLicenseBlueprint
    Properties:
      ProjectName: bda-project
      StandardOutputConfiguration: 
        Document:
          Extraction:
            Granularity:
              Types:
                - DOCUMENT
                - PAGE
                - ELEMENT
                - WORD
                - LINE
            BoundingBox:
              State: ENABLED
          GenerativeField:
            State: ENABLED
          OutputFormat:
            TextFormat:
              Types:
                - PLAIN_TEXT
                - MARKDOWN
                - HTML
                - CSV
            AdditionalFileFormat:
              State: ENABLED
        Image:
          Extraction:
            Category:
              State: ENABLED
              Types:
                - CONTENT_MODERATION
                - TEXT_DETECTION
                - LOGOS
            BoundingBox:
              State: ENABLED
          GenerativeField:
            State: ENABLED
            Types:
              - IMAGE_SUMMARY
              - IAB
        Video:
          Extraction:
            Category:
              State: ENABLED
              Types:
                - CONTENT_MODERATION
                - TEXT_DETECTION
                - TRANSCRIPT
                - LOGOS
            BoundingBox:
              State: ENABLED
          GenerativeField:
            State: ENABLED
            Types:
              - VIDEO_SUMMARY
              - IAB
              - CHAPTER_SUMMARY
        Audio:
          Extraction:
            Category:
              State: ENABLED
              Types:
                - AUDIO_CONTENT_MODERATION
                - TRANSCRIPT
                - TOPIC_CONTENT_MODERATION
          GenerativeField:
            State: ENABLED
            Types:
              - AUDIO_SUMMARY
              - IAB
              - TOPIC_SUMMARY
      CustomOutputConfiguration:
        Blueprints:
          - BlueprintArn: !GetAtt DrivingLicenseBlueprint.BlueprintArn
            BlueprintStage: !GetAtt DrivingLicenseBlueprint.BlueprintStage

Outputs:
  BlueprintArn:
    Description: ARN of the created Bedrock Data Automation Blueprint
    Value: !GetAtt DrivingLicenseBlueprint.BlueprintArn
    Export:
      Name: !Sub "${AWS::StackName}-BlueprintArn"
  
  BlueprintStage:
    Description: Stage of the created Bedrock Data Automation Blueprint
    Value: !GetAtt DrivingLicenseBlueprint.BlueprintStage
    Export:
      Name: !Sub "${AWS::StackName}-BlueprintStage"
  
  BDAProjectArn:
    Description: ARN of the created Bedrock Data Automation Project
    Value: !GetAtt BDAProject.ProjectArn
    Export:
      Name: !Sub "${AWS::StackName}-BDAProjectArn"